AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
  WafWebAcl:
    Type: "AWS::WAFv2::WebACL"
    Properties:
      Name: "maddy"
      Scope: "CLOUDFRONT"
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: "maddy"
        SampledRequestsEnabled: true
      Rules: []
      Description: "WAF"
Parameters: {}
Metadata: {}
Conditions: {}
